
[workspace.package]
name = "core_macro"
version = "0.1.0"
edition = "2021"
resover = "2"

[workspace.dependencies]
quote = "1.0.38"
syn = "2.0.96"
proc-macro2 = "1.0.93"
serde = { version = "1.0.217", features = ["derive"] }

[workspace]
members = ["core_macro", "final_test", "into_json"]
